version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eticketing
    ports: ["3306:3306"]
  api:
    build: .
    environment:
      DB_ENABLED: "true"
      DB_URL: jdbc:mysql://db:3306/eticketing
      DB_USER: root
      DB_PASS: root
      PORT: "8080"
    ports: ["8080:8080"]
    depends_on: [db]
